env: FLUTTER_GITHUB="https://github.com/flutter/flutter.git"

language: dart

dart: stable

dart_task: 
  - dartanalyzer
  - dartfmt
  - test

jobs:
  include:
    - stage: Flutter Test
      os: linux
      language: dart
      install: git clone $FLUTTER_GITHUB -b stable
      before_script: ./flutter/bin/flutter doctor
      script: ./flutter/bin/flutter test