name: flutter_firebase_auth_benchmark

author: Philippe Fanaro <philippefanaro@gmail.com>

description: >-
  A benchmark for Authentication through Firebase in Flutter.

homepage: https://github.com/psygo/flutter_firebase_auth_benchmark

repository: https://github.com/psygo/flutter_firebase_auth_benchmark

documentation: https://github.com/psygo/flutter_firebase_auth_benchmark

issue_tracker: https://github.com/psygo/flutter_firebase_auth_benchmark/issues

version: 1.0.0

environment:
  sdk: ">=2.5.1 <3.0.0"
  flutter: ^1.12.0

flutter:
  uses-material-design: true
  assets:
    - img/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  meta: ^1.1.8
  provider: ^4.0.4
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  flutter_svg: ^0.17.3+1